apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd
  name: k3s
spec:
  generators:
  - list:
      elements:
      - folder: external-services
        namespace: external-services
  template:
    metadata:
      name: '{{folder}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/kronolith1/k3s.git
        targetRevision: HEAD
        path: '{{folder}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true